require 'app/rompicker.rb'
require 'app/cpu.rb'
require 'app/display.rb'
require 'app/toggle_switch.rb'
require 'app/momentary_switch.rb'
require 'app/controls.rb'
require 'app/keyboard.rb'
require 'app/tick.rb'
